# Generated by Django 5.2.1 on 2025-07-31 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("i have a project in mind", "I have a project in mind"),
                            (
                                "i'm a developer looking for collaboration",
                                "I'm a developer looking for collaboration",
                            ),
                            ("i'm a recruiter", "I'm a recruiter"),
                            ("other", "Other"),
                        ],
                        default="i have a project in mind",
                        max_length=250,
                    ),
                ),
                ("message", models.TextField()),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
            },
        ),
    ]
