# Generated by Django 5.2.1 on 2025-09-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="email_ar",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="email_en",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="email_es",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="email_fr",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="message_ar",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="message_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="message_es",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="message_fr",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="name_ar",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="name_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="name_es",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="name_fr",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="subject_ar",
            field=models.CharField(
                choices=[
                    ("i have a project in mind", "I have a project in mind"),
                    (
                        "i'm a developer looking for collaboration",
                        "I'm a developer looking for collaboration",
                    ),
                    ("i'm a recruiter", "I'm a recruiter"),
                    ("other", "Other"),
                ],
                default="i have a project in mind",
                max_length=250,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="subject_en",
            field=models.CharField(
                choices=[
                    ("i have a project in mind", "I have a project in mind"),
                    (
                        "i'm a developer looking for collaboration",
                        "I'm a developer looking for collaboration",
                    ),
                    ("i'm a recruiter", "I'm a recruiter"),
                    ("other", "Other"),
                ],
                default="i have a project in mind",
                max_length=250,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="subject_es",
            field=models.CharField(
                choices=[
                    ("i have a project in mind", "I have a project in mind"),
                    (
                        "i'm a developer looking for collaboration",
                        "I'm a developer looking for collaboration",
                    ),
                    ("i'm a recruiter", "I'm a recruiter"),
                    ("other", "Other"),
                ],
                default="i have a project in mind",
                max_length=250,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="subject_fr",
            field=models.CharField(
                choices=[
                    ("i have a project in mind", "I have a project in mind"),
                    (
                        "i'm a developer looking for collaboration",
                        "I'm a developer looking for collaboration",
                    ),
                    ("i'm a recruiter", "I'm a recruiter"),
                    ("other", "Other"),
                ],
                default="i have a project in mind",
                max_length=250,
                null=True,
            ),
        ),
    ]
