# Generated by Django 5.2.1 on 2025-09-04 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0002_contact_email_ar_contact_email_en_contact_email_es_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="email_ar",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="email_fr",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="message_ar",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="message_fr",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="name_ar",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="name_fr",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="subject_ar",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="subject_fr",
        ),
    ]
