# Generated by Django 5.2.1 on 2025-06-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="portfolio_images/%Y/%m/%d/")),
                (
                    "preview_image",
                    models.ImageField(upload_to="portfolio_preview_images/%Y/%m/%d/"),
                ),
                ("project_url", models.URLField(blank=True, max_length=300, null=True)),
                ("stack", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "features_title",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("features_description", models.TextField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[("all", "All"), ("web", "Web "), ("app", "App")],
                        default="all",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Portfolio",
                "verbose_name_plural": "Portfolios",
                "ordering": ["-created"],
            },
        ),
    ]
