# Generated by Django 5.2.1 on 2025-08-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("qualifications", models.TextField(blank=True, null=True)),
                ("bio", models.TextField(blank=True, null=True)),
                ("blog_url", models.URLField(blank=True, max_length=300, null=True)),
                ("tech_stack", models.TextField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, max_length=15, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "social_links",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("image", models.ImageField(upload_to="about_images/%Y/%m/%d/")),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "freelance_status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("not_available", "Not Available"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "About",
                "verbose_name_plural": "Abouts",
            },
        ),
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("image", models.ImageField(upload_to="portfolio_images/%Y/%m/%d/")),
                (
                    "preview_image",
                    models.ImageField(upload_to="portfolio_preview_images/%Y/%m/%d/"),
                ),
                ("project_url", models.URLField(blank=True, max_length=300, null=True)),
                ("stack", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "features_title",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("features_description", models.TextField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[("app", "App"), ("web", "Web")], max_length=20
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Portfolio",
                "verbose_name_plural": "Portfolios",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("role", models.CharField(blank=True, max_length=100)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="testimonials/%Y/%m/%d/"
                    ),
                ),
                ("message", models.TextField()),
                ("rating", models.PositiveIntegerField(default=5)),
                ("is_approved", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Testimonial",
                "verbose_name_plural": "Testimonials",
                "ordering": ["-id"],
            },
        ),
    ]
