# Generated by Django 5.2.1 on 2025-06-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='category',
            field=models.CharField(choices=[('web', 'Web'), ('app', 'App')], max_length=20),
        ),
    ]
