# Generated by Django 5.2.1 on 2025-08-31 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_testimonial_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="project_status",
            field=models.CharField(
                choices=[("development", "Development"), ("production", "Production")],
                default="production",
                max_length=20,
            ),
        ),
    ]
