# Generated by Django 5.2.1 on 2025-09-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_portfolio_project_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="about",
            name="bio_ar",
            field=models.TextField(blank=True, null=True, verbose_name="Bio"),
        ),
        migrations.AddField(
            model_name="about",
            name="bio_en",
            field=models.TextField(blank=True, null=True, verbose_name="Bio"),
        ),
        migrations.AddField(
            model_name="about",
            name="bio_es",
            field=models.TextField(blank=True, null=True, verbose_name="Bio"),
        ),
        migrations.AddField(
            model_name="about",
            name="bio_fr",
            field=models.TextField(blank=True, null=True, verbose_name="Bio"),
        ),
        migrations.AddField(
            model_name="about",
            name="blog_url_ar",
            field=models.URLField(
                blank=True, max_length=300, null=True, verbose_name="Blog URL"
            ),
        ),
        migrations.AddField(
            model_name="about",
            name="blog_url_en",
            field=models.URLField(
                blank=True, max_length=300, null=True, verbose_name="Blog URL"
            ),
        ),
        migrations.AddField(
            model_name="about",
            name="blog_url_es",
            field=models.URLField(
                blank=True, max_length=300, null=True, verbose_name="Blog URL"
            ),
        ),
        migrations.AddField(
            model_name="about",
            name="blog_url_fr",
            field=models.URLField(
                blank=True, max_length=300, null=True, verbose_name="Blog URL"
            ),
        ),
        migrations.AddField(
            model_name="about",
            name="email_ar",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email"
            ),
        ),
        migrations.AddField(
            model_name="about",
            name="email_en",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email"
            ),
        ),
        migrations.AddField(
            model_name="about",
            name="email_es",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email"
            ),
        ),
        migrations.AddField(
            model_name="about",
            name="email_fr",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email"
            ),
        ),
        migrations.AddField(
            model_name="about",
            name="phone_ar",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Phone"
            ),
        ),
        migrations.AddField(
            model_name="about",
            name="phone_en",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Phone"
            ),
        ),
        migrations.AddField(
            model_name="about",
            name="phone_es",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Phone"
            ),
        ),
        migrations.AddField(
            model_name="about",
            name="phone_fr",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Phone"
            ),
        ),
        migrations.AddField(
            model_name="about",
            name="qualifications_ar",
            field=models.TextField(
                blank=True, null=True, verbose_name="Qualifications"
            ),
        ),
        migrations.AddField(
            model_name="about",
            name="qualifications_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="Qualifications"
            ),
        ),
        migrations.AddField(
            model_name="about",
            name="qualifications_es",
            field=models.TextField(
                blank=True, null=True, verbose_name="Qualifications"
            ),
        ),
        migrations.AddField(
            model_name="about",
            name="qualifications_fr",
            field=models.TextField(
                blank=True, null=True, verbose_name="Qualifications"
            ),
        ),
        migrations.AddField(
            model_name="about",
            name="social_links_ar",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Social Links"
            ),
        ),
        migrations.AddField(
            model_name="about",
            name="social_links_en",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Social Links"
            ),
        ),
        migrations.AddField(
            model_name="about",
            name="social_links_es",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Social Links"
            ),
        ),
        migrations.AddField(
            model_name="about",
            name="social_links_fr",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Social Links"
            ),
        ),
        migrations.AddField(
            model_name="about",
            name="tech_stack_ar",
            field=models.TextField(blank=True, null=True, verbose_name="Tech Stack"),
        ),
        migrations.AddField(
            model_name="about",
            name="tech_stack_en",
            field=models.TextField(blank=True, null=True, verbose_name="Tech Stack"),
        ),
        migrations.AddField(
            model_name="about",
            name="tech_stack_es",
            field=models.TextField(blank=True, null=True, verbose_name="Tech Stack"),
        ),
        migrations.AddField(
            model_name="about",
            name="tech_stack_fr",
            field=models.TextField(blank=True, null=True, verbose_name="Tech Stack"),
        ),
        migrations.AddField(
            model_name="about",
            name="title_ar",
            field=models.CharField(max_length=100, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="about",
            name="title_en",
            field=models.CharField(max_length=100, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="about",
            name="title_es",
            field=models.CharField(max_length=100, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="about",
            name="title_fr",
            field=models.CharField(max_length=100, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="category_ar",
            field=models.CharField(
                choices=[("app", "App"), ("web", "Web")],
                max_length=20,
                null=True,
                verbose_name="Category",
            ),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="category_en",
            field=models.CharField(
                choices=[("app", "App"), ("web", "Web")],
                max_length=20,
                null=True,
                verbose_name="Category",
            ),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="category_es",
            field=models.CharField(
                choices=[("app", "App"), ("web", "Web")],
                max_length=20,
                null=True,
                verbose_name="Category",
            ),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="category_fr",
            field=models.CharField(
                choices=[("app", "App"), ("web", "Web")],
                max_length=20,
                null=True,
                verbose_name="Category",
            ),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="features_description_ar",
            field=models.TextField(
                blank=True, null=True, verbose_name="Features Description"
            ),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="features_description_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="Features Description"
            ),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="features_description_es",
            field=models.TextField(
                blank=True, null=True, verbose_name="Features Description"
            ),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="features_description_fr",
            field=models.TextField(
                blank=True, null=True, verbose_name="Features Description"
            ),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="features_title_ar",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Features Title"
            ),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="features_title_en",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Features Title"
            ),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="features_title_es",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Features Title"
            ),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="features_title_fr",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Features Title"
            ),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="image_ar",
            field=models.ImageField(
                null=True, upload_to="portfolio_images/%Y/%m/%d/", verbose_name="Image"
            ),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="image_en",
            field=models.ImageField(
                null=True, upload_to="portfolio_images/%Y/%m/%d/", verbose_name="Image"
            ),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="image_es",
            field=models.ImageField(
                null=True, upload_to="portfolio_images/%Y/%m/%d/", verbose_name="Image"
            ),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="image_fr",
            field=models.ImageField(
                null=True, upload_to="portfolio_images/%Y/%m/%d/", verbose_name="Image"
            ),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="preview_image_ar",
            field=models.ImageField(
                null=True,
                upload_to="portfolio_preview_images/%Y/%m/%d/",
                verbose_name="Preview Image",
            ),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="preview_image_en",
            field=models.ImageField(
                null=True,
                upload_to="portfolio_preview_images/%Y/%m/%d/",
                verbose_name="Preview Image",
            ),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="preview_image_es",
            field=models.ImageField(
                null=True,
                upload_to="portfolio_preview_images/%Y/%m/%d/",
                verbose_name="Preview Image",
            ),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="preview_image_fr",
            field=models.ImageField(
                null=True,
                upload_to="portfolio_preview_images/%Y/%m/%d/",
                verbose_name="Preview Image",
            ),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="project_status_ar",
            field=models.CharField(
                choices=[("development", "Development"), ("production", "Production")],
                default="production",
                max_length=20,
                null=True,
                verbose_name="Project Status",
            ),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="project_status_en",
            field=models.CharField(
                choices=[("development", "Development"), ("production", "Production")],
                default="production",
                max_length=20,
                null=True,
                verbose_name="Project Status",
            ),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="project_status_es",
            field=models.CharField(
                choices=[("development", "Development"), ("production", "Production")],
                default="production",
                max_length=20,
                null=True,
                verbose_name="Project Status",
            ),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="project_status_fr",
            field=models.CharField(
                choices=[("development", "Development"), ("production", "Production")],
                default="production",
                max_length=20,
                null=True,
                verbose_name="Project Status",
            ),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="project_url_ar",
            field=models.URLField(
                blank=True, max_length=300, null=True, verbose_name="Project URL"
            ),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="project_url_en",
            field=models.URLField(
                blank=True, max_length=300, null=True, verbose_name="Project URL"
            ),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="project_url_es",
            field=models.URLField(
                blank=True, max_length=300, null=True, verbose_name="Project URL"
            ),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="project_url_fr",
            field=models.URLField(
                blank=True, max_length=300, null=True, verbose_name="Project URL"
            ),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="stack_ar",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="Stack"
            ),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="stack_en",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="Stack"
            ),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="stack_es",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="Stack"
            ),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="stack_fr",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="Stack"
            ),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="status_ar",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")],
                default="draft",
                max_length=20,
                null=True,
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="status_en",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")],
                default="draft",
                max_length=20,
                null=True,
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="status_es",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")],
                default="draft",
                max_length=20,
                null=True,
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="status_fr",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")],
                default="draft",
                max_length=20,
                null=True,
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="title_ar",
            field=models.CharField(max_length=100, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="title_en",
            field=models.CharField(max_length=100, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="title_es",
            field=models.CharField(max_length=100, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="title_fr",
            field=models.CharField(max_length=100, null=True, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="email_ar",
            field=models.EmailField(max_length=254, null=True, verbose_name="Email"),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="email_en",
            field=models.EmailField(max_length=254, null=True, verbose_name="Email"),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="email_es",
            field=models.EmailField(max_length=254, null=True, verbose_name="Email"),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="email_fr",
            field=models.EmailField(max_length=254, null=True, verbose_name="Email"),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="image_ar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="testimonials/%Y/%m/%d/",
                verbose_name="Image",
            ),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="image_en",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="testimonials/%Y/%m/%d/",
                verbose_name="Image",
            ),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="image_es",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="testimonials/%Y/%m/%d/",
                verbose_name="Image",
            ),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="image_fr",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="testimonials/%Y/%m/%d/",
                verbose_name="Image",
            ),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="message_ar",
            field=models.TextField(null=True, verbose_name="Message"),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="message_en",
            field=models.TextField(null=True, verbose_name="Message"),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="message_es",
            field=models.TextField(null=True, verbose_name="Message"),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="message_fr",
            field=models.TextField(null=True, verbose_name="Message"),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="name_ar",
            field=models.CharField(max_length=100, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="name_en",
            field=models.CharField(max_length=100, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="name_es",
            field=models.CharField(max_length=100, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="name_fr",
            field=models.CharField(max_length=100, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="rating_ar",
            field=models.PositiveIntegerField(
                default=5, null=True, verbose_name="Rating"
            ),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="rating_en",
            field=models.PositiveIntegerField(
                default=5, null=True, verbose_name="Rating"
            ),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="rating_es",
            field=models.PositiveIntegerField(
                default=5, null=True, verbose_name="Rating"
            ),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="rating_fr",
            field=models.PositiveIntegerField(
                default=5, null=True, verbose_name="Rating"
            ),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="role_ar",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Role"
            ),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="role_en",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Role"
            ),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="role_es",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Role"
            ),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="role_fr",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Role"
            ),
        ),
        migrations.AlterField(
            model_name="about",
            name="bio",
            field=models.TextField(blank=True, null=True, verbose_name="Bio"),
        ),
        migrations.AlterField(
            model_name="about",
            name="blog_url",
            field=models.URLField(
                blank=True, max_length=300, null=True, verbose_name="Blog URL"
            ),
        ),
        migrations.AlterField(
            model_name="about",
            name="city",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="City"
            ),
        ),
        migrations.AlterField(
            model_name="about",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created"),
        ),
        migrations.AlterField(
            model_name="about",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="about",
            name="freelance_status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("not_available", "Not Available"),
                ],
                default="available",
                max_length=20,
                verbose_name="Freelance Status",
            ),
        ),
        migrations.AlterField(
            model_name="about",
            name="image",
            field=models.ImageField(
                upload_to="about_images/%Y/%m/%d/", verbose_name="Image"
            ),
        ),
        migrations.AlterField(
            model_name="about",
            name="phone",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Phone"
            ),
        ),
        migrations.AlterField(
            model_name="about",
            name="qualifications",
            field=models.TextField(
                blank=True, null=True, verbose_name="Qualifications"
            ),
        ),
        migrations.AlterField(
            model_name="about",
            name="slug",
            field=models.SlugField(max_length=100, unique=True, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="about",
            name="social_links",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Social Links"
            ),
        ),
        migrations.AlterField(
            model_name="about",
            name="tech_stack",
            field=models.TextField(blank=True, null=True, verbose_name="Tech Stack"),
        ),
        migrations.AlterField(
            model_name="about",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="category",
            field=models.CharField(
                choices=[("app", "App"), ("web", "Web")],
                max_length=20,
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created"),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="features_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Features Description"
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="features_title",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Features Title"
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="image",
            field=models.ImageField(
                upload_to="portfolio_images/%Y/%m/%d/", verbose_name="Image"
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="preview_image",
            field=models.ImageField(
                upload_to="portfolio_preview_images/%Y/%m/%d/",
                verbose_name="Preview Image",
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="project_status",
            field=models.CharField(
                choices=[("development", "Development"), ("production", "Production")],
                default="production",
                max_length=20,
                verbose_name="Project Status",
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="project_url",
            field=models.URLField(
                blank=True, max_length=300, null=True, verbose_name="Project URL"
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="slug",
            field=models.SlugField(max_length=100, unique=True, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="stack",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="Stack"
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")],
                default="draft",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="testimonials/%Y/%m/%d/",
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="is_approved",
            field=models.BooleanField(default=False, verbose_name="Is Approved"),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="message",
            field=models.TextField(verbose_name="Message"),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="rating",
            field=models.PositiveIntegerField(default=5, verbose_name="Rating"),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="role",
            field=models.CharField(blank=True, max_length=100, verbose_name="Role"),
        ),
    ]
