# Generated by Django 5.2.1 on 2025-07-31 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_alter_testimonial_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("qualifications", models.TextField(blank=True, null=True)),
                ("bio", models.TextField(blank=True, null=True)),
                ("blog_url", models.URLField(blank=True, max_length=300, null=True)),
                ("tech_stack", models.TextField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, max_length=15, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "social_links",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("image", models.ImageField(upload_to="about_images/%Y/%m/%d/")),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "freelance_status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("not_available", "Not Available"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "About",
                "verbose_name_plural": "Abouts",
            },
        ),
    ]
