# Generated by Django 5.2.1 on 2025-09-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "portfolio",
            "0004_about_bio_ar_about_bio_en_about_bio_es_about_bio_fr_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolio",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="portfolio_images/%Y/%m/%d/",
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="image_ar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="portfolio_images/%Y/%m/%d/",
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="image_en",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="portfolio_images/%Y/%m/%d/",
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="image_es",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="portfolio_images/%Y/%m/%d/",
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="image_fr",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="portfolio_images/%Y/%m/%d/",
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="preview_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="portfolio_preview_images/%Y/%m/%d/",
                verbose_name="Preview Image",
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="preview_image_ar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="portfolio_preview_images/%Y/%m/%d/",
                verbose_name="Preview Image",
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="preview_image_en",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="portfolio_preview_images/%Y/%m/%d/",
                verbose_name="Preview Image",
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="preview_image_es",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="portfolio_preview_images/%Y/%m/%d/",
                verbose_name="Preview Image",
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="preview_image_fr",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="portfolio_preview_images/%Y/%m/%d/",
                verbose_name="Preview Image",
            ),
        ),
    ]
